name: Lektor site CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the site in the lektor container
      run: |
        docker run --rm  -v ${{ github.workspace }}:/opt/lektor softinstigate/lektor build -O ./dist

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        tar -cvf deploy.tar ./dist

    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        source: "deploy.tar"
        target: "destination/folder"
