name: Lektor site CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
      tags:
        description: "Test scenario tags"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the site in the lektor container
        run: |
          docker run --rm  -v ${{ github.workspace }}:/opt/lektor softinstigate/lektor build -O ./dist

      - name: copy dist/ folder via ssh
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "dist/"
          target: "/var/www/html/plug-web"
          strip_components: 1
          port: ${{ secrets.PORT }}
